name: Verify CHANGELOG.md
description: Verify CHANGELOG.md against Keep a Changelog format
runs:
  using: "composite"
  steps:
    - name: Verify Keep a changelog format
      shell: bash
      run: pip install python-kacl && kacl-cli verify
    - name: Verify if CHANGELOG.md is updated
      shell: bash
      run: |
        set -e
        if [[ "${{ github.event.head_commit.message }}" == *"[skip-cl]"* ]]; then
          echo "Skipping CHANGELOG.md update verification"
        fi

        gh pr diff | grep "diff --git a/CHANGELOG.md b/CHANGELOG.md" && echo 'OK!'