name: 'Piwik PRO godtools docker image push'
description: 'Installs godtools'
inputs:
  godtools-config:
    required: true
    description: godtools encrypted configuration
  godtools-key:
    required: true
    description: godtools encryption key
  image:
    required: true
    description: Image, that should be pushed to the registry
  registries:
    required: false
    default: acr
    description: List of names of the registries where an image should be pushed (ecr, acr, docker-hub, internal-acr).
runs:
  using: "composite"
  steps:
    - name: Push tmp docker image
      if: "!startsWith(github.ref, 'refs/tags')"
      shell: bash
      run: |
        docker tag ${{ inputs.image }} ${{ inputs.image }}:tmp-$(git rev-parse --short HEAD) && 
        godtools docker push --registry-id "${{ inputs.registries }}" ${{ inputs.image }}:tmp-$(git rev-parse --short HEAD)
      env:
        GODTOOLS_CONFIG: ${{ inputs.godtools-config }}
        GODTOOLS_KEY: ${{ inputs.godtools-key }}

    - name: Push production docker image
      if: startsWith(github.ref, 'refs/tags')
      shell: bash
      run: |
        docker tag ${{ inputs.image }} ${{ inputs.image }}:${{ github.ref_name }} &&
        godtools docker push --registry-id "${{ inputs.registries }}" ${{ inputs.image }}:${{ github.ref_name }}
      env:
        GODTOOLS_CONFIG: ${{ inputs.godtools-config }}
        GODTOOLS_KEY: ${{ inputs.godtools-key }}

