name: 'Piwik PRO godtools docker image push'
description: 'Installs godtools'
inputs:
  image:
    required: true
    description: Image, that should be pushed to the registry
  registries:
    required: false
    default: acr
    description: List of names of the registries where an image should be pushed (ecr, acr, docker_hub, internal_acr).
runs:
  using: "composite"
  steps:
    - name: Generate PiwikPRO access tokens
      uses: PiwikPRO/github-app-token-generator@v1
      id: get-token
      with:
        private-key: ${{ inputs.reporeader-private-key }}
        app-id: ${{ inputs.reporeader-application-id }}
    - name: Push tmp docker image
      if: "!startsWith(github.ref, 'refs/tags')"
      shell: bash
      run: |
        docker tag piwikprocloud/organization piwikprocloud/organization:tmp-$(git rev-parse --short HEAD) && 
        godtools docker push --registry-id "${{ inputs.include-registry }}" piwikprocloud/organization:tmp-$(git rev-parse --short HEAD)
      env:
        GODTOOLS_CONFIG: ${{ secrets.GODTOOLS_CONFIG }}
        GODTOOLS_KEY: ${{ secrets.GODTOOLS_KEY }}

    - name: Push production docker image
      if: startsWith(github.ref, 'refs/tags')
      shell: bash
      run: |
        docker tag piwikprocloud/organization piwikprocloud/organization:${{ github.ref_name }} &&
        godtools docker push --registry-id "${{ inputs.include-registry }}" piwikprocloud/organization:${{ github.ref_name }}
      env:
        GODTOOLS_CONFIG: ${{ secrets.GODTOOLS_CONFIG }}
        GODTOOLS_KEY: ${{ secrets.GODTOOLS_KEY }}
