name: 'Piwik PRO dependabot update changelog'
description: 'It updates changelog when new pull request is created by dependabot'
inputs:
  user-email:
    description: 'user email used to commit changes by dependabot'
    required: true
  user-name:
    description: 'user name used to commit changes by dependabot'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        ref: ${{ github.head_ref }}
    - name: Install and configure dependencies
      shell: bash
      run: |
        pip install python-kacl
        echo ${{ github.token }} | gh auth login --with-token
    - name: Add changelog entry
      shell: bash
      run: |
        PR_TITLE=`some_hardcoded_title`
        kacl-cli add security "$PR_TITLE" --modify
    - name: Commit and push changes
      shell: bash
      run: |
        git config --local user.email '${{ inputs.user-email }}' && git config --local user.name '${{ inputs.user-name }}'
        git add CHANGELOG.md && git commit -m 'Update changelog'
        git push "https://dependabot:${{ github.token }}@github.com/${{ github.repository }}.git" ${{ github.head_ref }}
