name: Static analysis
inputs:
  python-version:
    required: false
    description: Version of python
    default: "3.13.*"
  target-version:
    required: false
    description: Target version
    default: "py313"
  ruff-version:
    required: false
    description: Version of ruff
    default: "0.9.*"

runs:
  using: "composite"
  steps:
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install ruff
      shell: bash
      run: sudo pip install ruff==${{ inputs.ruff-version }}

    - name: Set target-version in pyproject.toml
      shell: bash
      run: |
        sed -i 's/target-version = ".*"/target-version = "${{ inputs.target-version }}"/' ${{ github.action_path }}/pyproject.toml
        grep 'target-version' ${{ github.action_path }}/pyproject.toml

    - name: Run ruff linter
      shell: bash
      run: ruff check . --config ${{ github.action_path }}/pyproject.toml

    - name: Run ruff formatter
      shell: bash
      run: ruff format --check . --config ${{ github.action_path }}/pyproject.toml