name: Static analysis
inputs:
  python-version:
    required: false
    description: Version of python
    default: "3.12.2"
  poetry-version:
    required: false
    description: Version of python
    default: "1.8.2"
  target-version:
    required: false
    description: Target version
    default: "py312"

runs:
  using: "composite"
  steps:
    - name: Install poetry ${{ inputs.poetry-version }}
      shell: bash
      run: curl -sSL https://install.python-poetry.org | POETRY_VERSION=${{ inputs.poetry-version }} python3 -

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'poetry'

    - name: Install python packages
      shell: bash
      run: poetry install --only=dev

    - name: Set target-version in pyproject.toml
      shell: bash
      run: |
        sed -i 's/target-version = ".*"/target-version = ${{ inputs.target-version }}/' ${{ github.action_path }}/pyproject.toml
        grep 'target-version' ${{ github.action_path }}/pyproject.toml

    - name: Run ruff linter
      shell: bash
      run: poetry run ruff check . --config ${{ github.action_path }}/pyproject.toml

    - name: Run ruff formatter
      shell: bash
      run: poetry run ruff format --check . --config ${{ github.action_path }}/pyproject.toml
