[tool.ruff]
line-length = 120
target-version = "py313"

[tool.ruff.lint]
select = [
    "E",   # General PEP8 compliance
    "F",   # Pyflakes for finding common issues
    "B",   # Bugbear for catching potential bugs and performance issues
    "UP",  # PyUpgrade for keeping up with Python 3.13 features,
    "C",   # Complexity checks
]
extend-select = [
    "I",  # Import order
    "ANN", # Type annotations
]
ignore = [
    "F811", # F811 `Redefinition of unused name` - fixtures that does not return value
    "D100", # Missing docstring in public module
    "D101", # Missing docstring in public class
    "D102", # Missing docstring in public method
    "D103", # Missing docstring in public function
    "D104", # Missing docstring in public package
    "D105", # Missing docstring in magic method
    "D106", # Missing docstring in public nested class
    "D107", # Missing docstring in __init__ method
    "ANN204", # ANN204 Missing return type annotation for special method `__init__`
]

# Ignore missing return type annotation,
# missing docstring in public class,
# missing type annotation for function argument
# missing-return-type-private-function
# Module imported but unused` - ignored because all __init__.py were marked with F401 because it does not contain __all__ variable
per-file-ignores = { "tests/*" = ["ANN201", "ANN202", "ANN001"], "conftest.py" = ["F401"], "__init__.py" = ["F401"] }