name: "Piwik PRO golang binary builder and releaser"
description: "Uses packr to build go program and exposes it as github release"
inputs:
  cgo-enabled:
    required: false
    description: CGO_ENABLED build flag, allows using C libraries
    default: "1"
  binary-name:
    required: true
    description: Name of the binary, that should be released
  main-file:
    required: false
    description: Name of the main file, that should be used for compilation
    default: main.go
  goos:
    required: false
    description: The name of the target operating system
    default: linux
  goarch:
    required: false
    description: The name of the target compilation architecture
    default: amd64
runs:
  using: "composite"
  steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: Update project version if cmd/version.go exists
      shell: bash
      run: |
        if [ -f "cmd/version.go" ]; then
          printf "package cmd\n\nconst projectVersion = \"$(echo $GITHUB_REF | cut -d / -f 3)\"" > cmd/version.go
        fi

    - name: Build binary
      shell: bash
      run: |
        go build -a -tags netgo -ldflags '-w -extldflags "-static"' -o ${{ inputs.binary-name }} ${{ inputs.main-file }}
      env:
        CGO_ENABLED: ${{ inputs.cgo-enabled }}
        GOOS: ${{ inputs.goos }}
        GOARCH: ${{ inputs.goarch }}

    - name: Release the binary if on tag
      uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ inputs.binary-name }}
