name: 'Piwik PRO golang binary builder and releaser'
description: 'Uses packr to build go program and exposes it as github release'
inputs:
  binary-name:
    required: true
    description: Name of the binary, that should be released
  main-file:
    required: false
    description: Name of the main file, that should be used for compilation
    default: main.go
runs:
  using: "composite"
  steps:

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.x

    - name: Update project version if cmd/version.go exists
      shell: bash
      run: |
        if [ -f "cmd/version.go" ]; then
          printf "package cmd\n\nconst projectVersion = \"$(echo $GITHUB_REF | cut -d / -f 3)\"" > cmd/version.go
        fi

    - name: Build binary
      shell: bash
      run: |
        CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -a -tags netgo -ldflags '-w -extldflags "-static"' -o ${{ inputs.binary-name }} ${{ inputs.main-file }}

    - name: Release the binary if on tag
      uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ inputs.binary-name }}
