name: AWS S3 Linter errors
description: Make sure, that each consecutive PR improves amount of active linter errors
inputs:
  python-version:
    required: false
    description: Version of python
    default: "3.10.x"
  aws-access-key-id:
    required: true
    description: AWS Access Key ID
  aws-secret-access-key:
    required: true
    description: AWS Secret Access Key
  head-linter-errors:
    required: true
    description: Amount of linter errors of the current branch
  threshold:
    required: false
    description: Amount of linter errors, that should be fixed with every PR
    default: '5'
  linter-config-id:
    required: false
    description: To avoid errors when linter configuration changes, you can put here eg. sha256 of your linter config file. If this value differs, the amount of linter errors between base and head will not be compared.
    default: ''
runs:
  using: composite
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - uses: unfor19/install-aws-cli-action@v1

    - name: Update current branch linter-errors (pull_request)
      if: ${{ github.event_name == 'pull_request' }}
      shell: bash
      run: |
        ${{ github.action_path }}/inclint.py --action update --head-linter-errors ${{ inputs.head-linter-errors }} --aws-aki ${{ inputs.aws-access-key-id }} --aws-sac "${{ inputs.aws-secret-access-key }}" --project ${{ github.repository }} --branch ${{ github.head_ref }}

    - name: Update current branch linter-errors (push)
      if: ${{ github.event_name == 'push' }}
      shell: bash
      run: |
        ${{ github.action_path }}/inclint.py --action update --head-linter-errors ${{ inputs.head-linter-errors }} --aws-aki ${{ inputs.aws-access-key-id }} --aws-sac "${{ inputs.aws-secret-access-key }}" --project ${{ github.repository }} --branch ${{ github.ref }} --linter-config-id "${{ inputs.linter-config-id }}"

    - name: Compare amount of linter errors
      shell: bash
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        ${{ github.action_path }}/inclint.py --action compare --head-linter-errors ${{ inputs.head-linter-errors }} --aws-aki ${{ inputs.aws-access-key-id }} --aws-sac "${{ inputs.aws-secret-access-key }}" --project ${{ github.repository }} --branch ${{ github.base_ref }}  --linter-config-id "${{ inputs.linter-config-id }}" --threshold ${{ inputs.threshold }}
