name: 'Piwik PRO godtools docker login'
description: 'Installs godtools'
inputs:
  registries:
    required: false
    default: acr, docker-hub
    description: List of registries to which login will be performed (ecr, acr, docker_hub, internal_acr).
runs:
  using: "composite"
  steps:
    - name: Login to docker registries
      shell: bash
      run: godtools docker login --registry-id "${{ inputs.include-registry }}"
      env:
        GODTOOLS_CONFIG: ${{ secrets.GODTOOLS_CONFIG }}
        GODTOOLS_KEY: ${{ secrets.GODTOOLS_KEY }}
