name: 'Piwik PRO godtools docker login'
description: 'Installs godtools'
inputs:
  godtools-config:
    required: true
    description: godtools encrypted configuration
  godtools-key:
    required: true
    description: godtools encryption key
  registries:
    required: false
    default: acr, docker-hub
    description: List of registries to which login will be performed (ecr, acr, docker_hub, internal_acr).
runs:
  using: "composite"
  steps:
    - name: Login to docker registries
      shell: bash
      run: godtools docker login --registry-id "${{ inputs.include-registry }}"
      env:
        GODTOOLS_CONFIG: ${{ inputs.godtools-config }}
        GODTOOLS_KEY: ${{ inputs.godtools-key }}
