name: 'Piwik PRO godtools docker login'
description: 'Installs godtools'
inputs:
  godtools-config:
    required: true
    description: godtools encrypted configuration
  godtools-key:
    required: true
    description: godtools encryption key
  registries:
    required: false
    default: acr, docker-hub
    description: List of registries to which login will be performed (ecr, acr, docker-hub, internal-acr).
runs:
  using: "composite"
  steps:
    - name: Configure credential helper for docker
      shell: bash
      run: |
        curl -sL https://github.com/docker/docker-credential-helpers/releases/download/v0.8.0/docker-credential-secretservice-v0.8.0.linux-amd64 > docker-credential-secretservice &&
        chmod +x docker-credential-secretservice &&
        sudo mv docker-credential-secretservice /usr/local/bin/docker-credential-secretservice
    - name: Setup credstore secretservice in docker config
      shell: bash
      run: |
        mkdir -p ~/.docker &&
        echo '{"credsStore":"secretservice"}' > ~/.docker/config.json
    - name: Login to docker registries
      shell: bash
      run: godtools docker login --registry-id "${{ inputs.registries }}"
      env:
        GODTOOLS_CONFIG: ${{ inputs.godtools-config }}
        GODTOOLS_KEY: ${{ inputs.godtools-key }}
