name: 'Setup integration tests'
description: 'Sets up golang, python, installs local python package'
inputs:
  test-directory:
    required: false
    description: Name of the directory the tests are stored in
    default: "tests"
  python-version:
    description: "Python version that will be used in operator tests"
    required: false
    default: "3.10"
runs:
  using: "composite"
  steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.23.x"

    - name: Install Poetry
      uses: snok/install-poetry@v1.3.4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        architecture: "x64"
        cache: "poetry"
        cache-dependency-path: |
          toolkit/poetry.lock
          poetry.lock

    - name: Install dependencies
      shell: bash
      run: cd ${{ inputs.test-directory }} && poetry install
