name: 'Setup integration tests'
description: 'Sets up golang, python, installs local python package'
inputs:
  test-directory:
    required: false
    description: Name of the directory the tests are stored in
    default: "tests"
  python-version:
    description: "Python version that will be used in operator tests"
    required: false
    default: "3.10"
runs:
  using: "composite"
  steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.23.x"

    - name: Install uv
      uses: astral-sh/setup-uv@v6.6.1
      with:
        python-version: ${{ inputs.python-version }}
        enable-cache: true

    - name: Install Python
      shell: bash
      run: uv python install

    - name: Install dependencies
      shell: bash
      run: cd ${{ inputs.test-directory }} && uv sync
