name: 'Get Kubeconfig from 1Password'
description: "Gets a kubeconfig from specified 1Password vault/item"
inputs:
  op-sa-token:
    required: true
    description: "1Password Service Account Token"
  op-vault:
    required: true
    description: "1Password Vault"
    default: "Promil-preprod-gha-kubeconfigs"
  op-item:
    required: true
    description: "1Password Item"
outputs:
  kubeconfig:
    description: Value from 1Password Item.kubeconfig
    value: ${{ steps.decode-kubeconfig.outputs.kubeconfig }}

runs:
  using: "composite"
  steps:
  - name: Install 1Password CLI
    uses: 1password/install-cli-action@v1
    with:
      version: 2.30.0

  - name: Get Kubeconfig from 1Password
    id: get-kubeconfig
    env:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ inputs.op-sa-token }}
    shell: bash
    run: | 
      encoded=$(op item get ${{ inputs.op-item }} --vault=${{ inputs.op-vault }} --fields label=kubeconfig --reveal | tr -d "\n" )
      echo "::add-mask::$encoded"
      echo "encoded<<EOF"$'\n'"$encoded"$'\n'EOF >> "$GITHUB_OUTPUT"
  
  - name: Decode kubeconfig
    id: decode-kubeconfig
    shell: bash
    run: echo "kubeconfig<<EOF"$'\n'"$(echo '${{ steps.get-kubeconfig.outputs.encoded }}' | tr -d "\"" | base64 --decode)"$'\n'EOF >> "$GITHUB_OUTPUT"
