name: "Piwik PRO cosign download"
description: "Download cosign binary"
inputs:
  version:
    required: false
    description: "Specific release id, selected from https://github.com/sigstore/cosign/releases"
    # Find ID by tag:
    # curl https://api.github.com/repos/sigstore/cosign/releases | jq '.[] | select(.tag_name == "v2.2.0").id'
    default: "139369855" # v2.2.3
runs:
  using: "composite"
  steps:
    - name: "Download binary"
      shell: bash
      run: |
        URL=`curl -s https://api.github.com/repos/sigstore/cosign/releases/${{ inputs.version }} | jq -r '.assets[] | select(.name=="cosign-linux-amd64") | .browser_download_url'`;
        wget -q $URL --output-document cosign;
        chmod +x cosign;
        mkdir -p $HOME/.local/bin;
        mv cosign $HOME/.local/bin;
