version: "2"
linters:
  default: none
  enable:
    - depguard
    - dogsled
    - dupl
    - funlen
    - gocognit
    - goconst
    - gocyclo
    - godox
    - gosec
    - govet
    - lll
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    depguard:
      rules:
        Main:
          list-mode: lax
          files:
            - $all
            - '!$test'
          deny:
            - pkg: reflect
              desc: Please don't use reflect package
    dupl:
      threshold: 95
    funlen:
      lines: 65
      statements: 40
    gocognit:
      min-complexity: 25
    goconst:
      min-occurrences: 4
    lll:
      line-length: 120
    staticcheck:
      checks: ["all", "-ST1005"]
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
