name: 'Piwik PRO dtools setup job'
description: 'Installs Dtools'
inputs:
  reporeader-private-key:
    required: true
    description: Private key for token generator application
  reporeader-application-id:
    required: true
    description: Application ID of token generator application
  dtools-token:
    required: true
    description: Decryption token for dtools
  include-registry:
    required: true
    default: acr
    description: List of names of the registries where an image should be pushed (ecr, acr, docker_hub, internal_acr). Possible field delimiters are space, semicolon and comma.
runs:
  using: "composite"
  steps:

    - name: Generate PiwikPRO access tokens
      uses: PiwikPRO/github-app-token-generator@v1
      id: get-token
      with:
        private-key: ${{ inputs.reporeader-private-key }}
        app-id: ${{ inputs.reporeader-application-id }}
    - name: Parse register names and render args for dtools
      id: render-dtools-registry-args
      shell: bash
      run: |
        DTOOLS_ARGS=`echo "${{ inputs.include-registry }}" | sed "s/[ ;,]/\n/g" |  awk 'NF {sarg="--include-registry "$0; printf "%s ",sarg}'`;
        echo "args=$DTOOLS_ARGS" >> $GITHUB_OUTPUT;
    - name: Install dtools
      shell: bash
      env:
        PP_GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}
        PP_DTOOLS_TOKEN: ${{ inputs.dtools-token }}
      run: |
        curl -H "Authorization: token $PP_GITHUB_TOKEN" -H 'Accept: application/vnd.github.v3.raw' 'https://api.github.com/repos/PiwikPRO/Developers-Tools/contents/scripts/download-dtools.sh' | bash
        dtools dcr login ${{ steps.render-dtools-registry-args.outputs.args }}
