name: 'Piwik PRO dtools push'
description: 'Pushes docker images with dtools'
inputs:
  dtools-token:
    required: true
    description: Decryption token for dtools
  image:
    required: true
    description: Image, that should be pushed to the registry
  destination-tag:
    required: false
    default: ${{ github.ref_name }}
    description: Image tag, that should be pushed to the registry
  include-registry:
    required: true
    default: acr
    description: List of names of the registries where an image should be pushed (ecr, acr, docker_hub, internal_acr). Possible field delimiters are space, semicolon and comma.
runs:
  using: "composite"
  steps:
    - name: Parse register names and render args for dtools
      id: render-dtools-registry-args
      shell: bash
      run: |
        DTOOLS_ARGS=`echo "${{ inputs.include-registry }}" | sed "s/[ ;,]/\n/g" |  awk 'NF {sarg="--include-registry "$0; printf "%s ",sarg}'`;
        echo "args=$DTOOLS_ARGS" >> $GITHUB_OUTPUT;
    - name: Push the image
      shell: bash
      env:
        PP_DTOOLS_TOKEN: ${{ inputs.dtools-token }}
      run: |
        dtools dcr push --image ${{ inputs.image }} --dest-tag ${{ inputs.destination-tag }} ${{ steps.render-dtools-registry-args.outputs.args }}
