name: Check if CHANGELOG.md is updated
description: Check if CHANGELOG.md is updated
inputs:
  github-token:
    required: true
    description: GitHub token for GitHub CLI
runs:
  using: "composite"
  steps:
    - name: Verify if CHANGELOG.md is updated
      shell: bash
      run: |
        if [[ "${{ github.event.head_commit.message }}" == *"[skip-cl]"* ]]; then
          echo "Skipping CHANGELOG.md update verification"
          exit
        fi

        gh pr diff | grep "diff --git a/CHANGELOG.md b/CHANGELOG.md" && echo 'OK!'
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}