name: 'Benchmark summary compiler'
inputs:
  benchmark_path:
    default: "."
inputs:
  reports_path:
    default: "."
outputs:
  report:
    description: "Compiled report"
    value: ${{ steps.compile.outputs.report }}
runs:
  using: 'composite'
  steps:

    - name: Prepare the report
      id: compile
      shell: bash
      run: |
        REPORT=$(python ${{ github.action_path }}/script/cli.py --reports_path ${{ inputs.reports_path }} --benchmark_path ${{ inputs.benchmark_path }})
        echo "report<<EOF" >> $GITHUB_OUTPUT
        echo "${REPORT}" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
