name: 'Lint python project'
description: 'Runs few python linter'
inputs:
  python-version:
    required: false
    description: Version of python
    default: "3.10.x"
  use-black:
    required: false
    description: Use black linter
    default: true
  use-flake:
    required: false
    description: Use Flake8 linter
    default: true
  use-isort:
    required: false
    description: Use Isort linter
    default: true
runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Run isort linter
      if: ${{ inputs.use-isort == 'true' }}
      uses: jamescurtin/isort-action@f555d1d11ca0529654eb6d1f017f9e4a269ffa7f
      with:
        configuration: --check-only --diff --settings-path ${{ github.action_path }}/.isort.cfg
        requirementsFiles: ${{ inputs.requirements_files }} 
    - name: Run Black linter
      if: ${{ inputs.use-black == 'true' }}
      uses: psf/black@ae2c0758c9e61a385df9700dc9c231bf54887041
      with:
        options: --check --config ${{ github.action_path }}/pyproject.toml
        src: "."
        version: 23.12.1
    - name: Run flake8 linter
      if: ${{ inputs.use-flake == 'true' }}
      uses: py-actions/flake8@6b71483a8fe60d4cb967d3aa4ee56e5e52711d30
      with:
        args: "--config ${{ github.action_path }}/flake8.ini"