name: 'Piwik PRO godtools s3 download'
description: 'Downloads content from s3'
inputs:
  godtools-config:
    required: true
    description: godtools encrypted configuration
  godtools-key:
    required: true
    description: godtools encryption key
  data:
    required: true
    description: What to download
  ref:
    required: false
    default: master
    description: Revision
runs:
  using: "composite"
  steps:
    - name: Download data fom s3
      shell: bash
      run: |
        godtools s3 download ${{ inputs.data }} --ref ${{ inputs.ref }}
      env:
        GODTOOLS_CONFIG: ${{ inputs.godtools-config }}
        GODTOOLS_KEY: ${{ inputs.godtools-key }}
