name: 'Upload to S3'
description: 'Upload recursively to s3.'
inputs:
  src-path:
    required: false
    description: Path to dir that may be uploaded. Path must be relative to `github.workspace`. 
    default: 'artifacts/'
  dst-path:
    required: false
    description: Path to destination dir. Must end with '/'.
    default: "${{ github.repository }}/@${{ github.ref_name }}/artifacts/"
  aws-access-key-id: 
    required: true
    description: AWS Access Key ID
  aws-secret-access-key:
    required: true
    description: AWS Secret Access Key
  aws-bucket:
    required: true
    description: AWS Bucket
  aws-region:
    required: false
    description: AWS Region
    default: eu-central-1
  echo-destination-index-html:
    required:  false
    description: Print url to index.html in copied dir. 
    default: 'true'
  aws-http-proxy:
    required: false
    description: URI for aws-cli HTTP proxy
  aws-https-proxy:
    required: false
    description: URI for aws-cli HTTPS proxy
runs:
  using: 'composite'
  steps:
    - name: Install s5cmd
      shell: bash
      run: |
        S5CMD_VERSION="2.3.0"
        curl -fsSL "https://github.com/peak/s5cmd/releases/download/v${S5CMD_VERSION}/s5cmd_${S5CMD_VERSION}_Linux-64bit.tar.gz" -o /tmp/s5cmd.tar.gz
        sudo tar xzf /tmp/s5cmd.tar.gz -C /usr/local/bin s5cmd

    - name: Generate index.html if it doesn't exist
      if: ${{ inputs.echo-destination-index-html == 'true' }}
      shell: bash
      run: python ${{ github.action_path }}/create-index-html-if-not-exists.py ${{ github.workspace }}/${{ inputs.src-path }}

    - name: Copy to s3
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        AWS_DEFAULT_REGION: ${{ inputs.aws-region }}
        HTTP_PROXY: ${{ inputs.aws-http-proxy }}
        HTTPS_PROXY: ${{ inputs.aws-https-proxy }}
      run: s5cmd --log error cp "${{ github.workspace }}/${{ inputs.src-path }}*" "s3://${{ inputs.aws-bucket }}/${{ inputs.dst-path }}" || echo "No objects found at ${{ github.workspace }}/${{ inputs.src-path }}"

    - name: Report URL
      if: ${{ inputs.echo-destination-index-html == 'true' }}
      shell: bash
      run: echo https://${{ inputs.aws-bucket }}.s3.amazonaws.com/${{ inputs.dst-path }}index.html
