name: Pull and Push image to ghcr
on:
    workflow_dispatch:
        inputs:
            image-to-pull:
                description: Name of image you want to import to ghcr
                required: true
permissions:
    packages: write
env:
    REGISTRY: ghcr.io
    IMAGE_TO_PUSH: ghcr.io/piwikpro/${{ inputs.image-to-pull }}
jobs:
    pull_and_push:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
          - name: Pull image
            run: docker pull ${{ inputs.image-to-pull }}
          - name: Tag image
            run: docker tag ${{ inputs.image-to-pull }} ${{ env.IMAGE_TO_PUSH }}
          - name: Login to ghcr
            uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
            with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
          - name: Push image to ghcr
            run: docker push ${{ env.IMAGE_TO_PUSH }}
